os: linux
arch: amd64
dist: bionic
language: go
go:
- "1.14.x"
env:
  global:
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
before_install:
  - sudo apt-get -y install make
script: make all
branches:
  only: # safelist
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
