apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: conjur-operator-conjur-authenticator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-operator-conjur-authenticator
subjects:
- kind: ServiceAccount
  name: conjur-operator-conjur-oss
  namespace: conjur
