# permissions for end users to view conjurs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-viewer-role
rules:
- apiGroups:
  - oss.cyberark.com
  resources:
  - conjurs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oss.cyberark.com
  resources:
  - conjurs/status
  verbs:
  - get
