apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: conjur-operator-manager-role
subjects:
- kind: ServiceAccount
  name: conjur-operator-manager
  namespace: conjur
