apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"oss.cyberark.com/v1alpha1","kind":"Conjur","metadata":{"name":"example"},"spec":{"account":"default"}}]'
    capabilities: Basic Install
    categories: Security
    certified: "false"
    containerImage: https://quay.io/repository/jmckind/conjur-operator:latest
    createdAt: "2020-07-29 15:32:33"
    description: A seamless open source interface to securely authenticate, control and audit non-human access across tools, applications, containers and cloud environments via robust secrets management.
    operators.operatorframework.io/builder: operator-sdk-v1.0.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    repository: https://github.com/jmckind/conjur-operator
    support: Conjur Community
  name: conjur-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Conjur is the representation of the desired state for a Conjur OSS environment.
      displayName: Conjur
      kind: Conjur
      name: conjurs.oss.cyberark.com
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: Pod
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: StatefulSet
        name: ""
        version: apps/v1
      specDescriptors:
      - description: The name of the Conjur account to be used.
        displayName: Account
        path: account
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Phase is a simple, high-level summary of where the Conjur is in its lifecycle.
        displayName: Phase
        path: phase
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1alpha1
  description: |
    ## Overview

    The Conjur OSS Operator manages the full lifecycle for [Conjur OSS](https://www.conjur.org/) and it's
    components. The operator's goal is to automate the tasks required when operating a Conjur OSS environment.

    ## Usage

    Deploy a basic Conjur OSS environment by creating a new Conjur resource in the namespace where the operator is installed.

    ```
    apiVersion: oss.cyberark.com/v1alpha1
    kind: Conjur
    metadata:
      name: example
    spec:
      account: default
    ```

    See the [documentation](https://conjur-operator.readthedocs.io) and examples on
    [github](https://github.com/jmckind/conjur-operator) for more information.
  displayName: Conjur OSS Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgaW5rc2NhcGU6ZXhwb3J0LXlkcGk9Ijk2IgogICBpbmtzY2FwZTpleHBvcnQteGRwaT0iOTYiCiAgIGlua3NjYXBlOmV4cG9ydC1maWxlbmFtZT0iL2hvbWUvam9obi9zcmMvam1ja2luZC9jb25qdXItb3BlcmF0b3IvZG9jcy9hc3NldHMvY29uanVyLWxvZ28ucG5nIgogICB2aWV3Qm94PSIwIDAgNjMuOTk5OTk3IDYzLjk5OTk5OSIKICAgdmVyc2lvbj0iMS4xIgogICBpZD0ic3ZnNTQiCiAgIHNvZGlwb2RpOmRvY25hbWU9ImNvbmp1ci1sb2dvLnN2ZyIKICAgd2lkdGg9IjY0IgogICBoZWlnaHQ9IjY0IgogICBpbmtzY2FwZTp2ZXJzaW9uPSIxLjAgKDQwMzVhNGZiNDksIDIwMjAtMDUtMDEpIj4KICA8bWV0YWRhdGEKICAgICBpZD0ibWV0YWRhdGE1OCI+CiAgICA8cmRmOlJERj4KICAgICAgPGNjOldvcmsKICAgICAgICAgcmRmOmFib3V0PSIiPgogICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2Uvc3ZnK3htbDwvZGM6Zm9ybWF0PgogICAgICAgIDxkYzp0eXBlCiAgICAgICAgICAgcmRmOnJlc291cmNlPSJodHRwOi8vcHVybC5vcmcvZGMvZGNtaXR5cGUvU3RpbGxJbWFnZSIgLz4KICAgICAgICA8ZGM6dGl0bGU+QXNzZXQgMjg8L2RjOnRpdGxlPgogICAgICA8L2NjOldvcms+CiAgICA8L3JkZjpSREY+CiAgPC9tZXRhZGF0YT4KICA8c29kaXBvZGk6bmFtZWR2aWV3CiAgICAgaW5rc2NhcGU6ZG9jdW1lbnQtcm90YXRpb249IjAiCiAgICAgcGFnZWNvbG9yPSIjZmZmZmZmIgogICAgIGJvcmRlcmNvbG9yPSIjNjY2NjY2IgogICAgIGJvcmRlcm9wYWNpdHk9IjEiCiAgICAgb2JqZWN0dG9sZXJhbmNlPSIxMCIKICAgICBncmlkdG9sZXJhbmNlPSIxMCIKICAgICBndWlkZXRvbGVyYW5jZT0iMTAiCiAgICAgaW5rc2NhcGU6cGFnZW9wYWNpdHk9IjAiCiAgICAgaW5rc2NhcGU6cGFnZXNoYWRvdz0iMiIKICAgICBpbmtzY2FwZTp3aW5kb3ctd2lkdGg9IjI2MjEiCiAgICAgaW5rc2NhcGU6d2luZG93LWhlaWdodD0iMTgzNCIKICAgICBpZD0ibmFtZWR2aWV3NTYiCiAgICAgc2hvd2dyaWQ9ImZhbHNlIgogICAgIGlua3NjYXBlOnpvb209IjQuNjMxMDU5NyIKICAgICBpbmtzY2FwZTpjeD0iMTMwLjMxNTc1IgogICAgIGlua3NjYXBlOmN5PSIyOC41NDMiCiAgICAgaW5rc2NhcGU6d2luZG93LXg9IjM5ODgiCiAgICAgaW5rc2NhcGU6d2luZG93LXk9IjE1NCIKICAgICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIwIgogICAgIGlua3NjYXBlOmN1cnJlbnQtbGF5ZXI9IkxheWVyXzEtMiIgLz4KICA8ZGVmcwogICAgIGlkPSJkZWZzNCI+CiAgICA8c3R5bGUKICAgICAgIGlkPSJzdHlsZTIiPi5jbHMtMXtmaWxsOiM0YzhlY2M7fS5jbHMtMntmaWxsOiMyZjc0YjA7fS5jbHMtM3tmaWxsOiM4MDgwODM7fS5jbHMtNHtmaWxsOiM1YTVhNWQ7fS5jbHMtNXtmaWxsOiNmZmY7fTwvc3R5bGU+CiAgPC9kZWZzPgogIDx0aXRsZQogICAgIGlkPSJ0aXRsZTYiPkFzc2V0IDI4PC90aXRsZT4KICA8ZwogICAgIGlkPSJMYXllcl8yIgogICAgIGRhdGEtbmFtZT0iTGF5ZXIgMiI+CiAgICA8ZwogICAgICAgaWQ9IkxheWVyXzEtMiIKICAgICAgIGRhdGEtbmFtZT0iTGF5ZXIgMSI+CiAgICAgIDxwb2x5Z29uCiAgICAgICAgIGNsYXNzPSJjbHMtMSIKICAgICAgICAgcG9pbnRzPSIxOS4xMiwxMS4zNSAxOS4xMiwwIDAsMTEuMDUgOS44NSwxNi43MiAiCiAgICAgICAgIGlkPSJwb2x5Z29uOCIKICAgICAgICAgdHJhbnNmb3JtPSJtYXRyaXgoMS40MzEzNDg2LDAsMCwxLjQzMTM0ODYsNS4yOTcyODY4LDAuNDkyMDQ0MykiIC8+CiAgICAgIDxwb2x5Z29uCiAgICAgICAgIGNsYXNzPSJjbHMtMiIKICAgICAgICAgcG9pbnRzPSIyOC40MywyNy40MiAzOC4yNiwyMS43NCAzOC4yNiwzMy4wOSAxOS4xNiw0NC4xMyAxOS4xNCwzMi43OSAiCiAgICAgICAgIGlkPSJwb2x5Z29uMTAiCiAgICAgICAgIHRyYW5zZm9ybT0ibWF0cml4KDEuNDMxMzQ4NiwwLDAsMS40MzEzNDg2LDUuMjk3Mjg2OCwwLjQ5MjA0NDMpIiAvPgogICAgICA8cG9seWdvbgogICAgICAgICBjbGFzcz0iY2xzLTIiCiAgICAgICAgIHBvaW50cz0iMjguNDEsMTYuNzEgMzguMjMsMTEuMDMgMTkuMTIsMCAxOS4xMiwxMS4zNSAiCiAgICAgICAgIGlkPSJwb2x5Z29uMTIiCiAgICAgICAgIHRyYW5zZm9ybT0ibWF0cml4KDEuNDMxMzQ4NiwwLDAsMS40MzEzNDg2LDUuMjk3Mjg2OCwwLjQ5MjA0NDMpIiAvPgogICAgICA8cG9seWdvbgogICAgICAgICBjbGFzcz0iY2xzLTEiCiAgICAgICAgIHBvaW50cz0iOS44NSwyNy40MyAwLjAzLDMzLjEyIDE5LjE2LDQ0LjEzIDE5LjE0LDMyLjc4ICIKICAgICAgICAgaWQ9InBvbHlnb24xNCIKICAgICAgICAgdHJhbnNmb3JtPSJtYXRyaXgoMS40MzEzNDg2LDAsMCwxLjQzMTM0ODYsNS4yOTcyODY4LDAuNDkyMDQ0MykiIC8+CiAgICAgIDxwb2x5Z29uCiAgICAgICAgIGNsYXNzPSJjbHMtMiIKICAgICAgICAgcG9pbnRzPSI5Ljg1LDE2LjcyIDAsMTEuMDUgMC4wMywzMy4xMiA5Ljg1LDI3LjQzICIKICAgICAgICAgaWQ9InBvbHlnb24xNiIKICAgICAgICAgdHJhbnNmb3JtPSJtYXRyaXgoMS40MzEzNDg2LDAsMCwxLjQzMTM0ODYsNS4yOTcyODY4LDAuNDkyMDQ0MykiIC8+CiAgICAgIDxwb2x5Z29uCiAgICAgICAgIGNsYXNzPSJjbHMtMyIKICAgICAgICAgcG9pbnRzPSIyOC40MSwxNi43MSAyOC40MSwyNy40MyAxOS4xMiwyMi4wNyAxOS4xMiwxMS4zNCAiCiAgICAgICAgIGlkPSJwb2x5Z29uMTgiCiAgICAgICAgIHRyYW5zZm9ybT0ibWF0cml4KDEuNDMxMzQ4NiwwLDAsMS40MzEzNDg2LDUuMjk3Mjg2OCwwLjQ5MjA0NDMpIiAvPgogICAgICA8cG9seWxpbmUKICAgICAgICAgY2xhc3M9ImNscy00IgogICAgICAgICBwb2ludHM9IjE5LjEyIDExLjM0IDkuODUgMTYuNzIgOS44NSAyNy40MyAxOS4xMiAyMi4wNyAxOS4xMiAxMS4zNSIKICAgICAgICAgaWQ9InBvbHlsaW5lMjAiCiAgICAgICAgIHRyYW5zZm9ybT0ibWF0cml4KDEuNDMxMzQ4NiwwLDAsMS40MzEzNDg2LDUuMjk3Mjg2OCwwLjQ5MjA0NDMpIiAvPgogICAgPC9nPgogIDwvZz4KPC9zdmc+Cg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - security
  links:
  - name: Documentation
    url: https://conjur-operator.readthedocs.io
  - name: Source Code
    url: https://github.com/jmckind/conjur-operator
  maintainers:
  - email: john.mckenzie@redhat.com
    name: John McKenzie
  maturity: alpha
  provider:
    name: Conjur Community
    url: https://www.conjur.org
  version: 0.0.1
